# CMake generated Testfile for 
# Source directory: /home/yevyes/Nils/NilsToyProblem
# Build directory: /home/yevyes/Nils/NilsToyProblem
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(academy_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "academy")
SET_TESTS_PROPERTIES(academy_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(soccer_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "soccer")
SET_TESTS_PROPERTIES(soccer_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(batchdist_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "batchdist")
SET_TESTS_PROPERTIES(batchdist_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(batchdistrob_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "batchdistrob")
SET_TESTS_PROPERTIES(batchdistrob_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(batchdistRobEx_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "batchdistRobEx")
SET_TESTS_PROPERTIES(batchdistRobEx_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(batchdistUT_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "batchdistUT")
SET_TESTS_PROPERTIES(batchdistUT_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(brac_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "brac")
SET_TESTS_PROPERTIES(brac_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(brgr1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "brgr1")
SET_TESTS_PROPERTIES(brgr1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(brgr2_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "brgr2")
SET_TESTS_PROPERTIES(brgr2_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(ccbat_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "ccbat")
SET_TESTS_PROPERTIES(ccbat_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(ccrane_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "ccrane")
SET_TESTS_PROPERTIES(ccrane_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(chain1d_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "chain1d")
SET_TESTS_PROPERTIES(chain1d_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(chain_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "chain")
SET_TESTS_PROPERTIES(chain_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(container_bridge_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "container_bridge")
SET_TESTS_PROPERTIES(container_bridge_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(cstr_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "cstr")
SET_TESTS_PROPERTIES(cstr_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(cstr_est_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "cstr_est")
SET_TESTS_PROPERTIES(cstr_est_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(dcbat1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "dcbat1")
SET_TESTS_PROPERTIES(dcbat1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(dcbat2_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "dcbat2")
SET_TESTS_PROPERTIES(dcbat2_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(dcbat3_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "dcbat3")
SET_TESTS_PROPERTIES(dcbat3_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(eason_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "eason")
SET_TESTS_PROPERTIES(eason_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(eocar1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "eocar1")
SET_TESTS_PROPERTIES(eocar1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(eocar2_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "eocar2")
SET_TESTS_PROPERTIES(eocar2_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(extrosen_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "extrosen")
SET_TESTS_PROPERTIES(extrosen_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(fedbat1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "fedbat1")
SET_TESTS_PROPERTIES(fedbat1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(fedbat1m_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "fedbat1m")
SET_TESTS_PROPERTIES(fedbat1m_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(fedbat2_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "fedbat2")
SET_TESTS_PROPERTIES(fedbat2_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(fedbat2m_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "fedbat2m")
SET_TESTS_PROPERTIES(fedbat2m_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(fedbat3_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "fedbat3")
SET_TESTS_PROPERTIES(fedbat3_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(fedbat3m_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "fedbat3m")
SET_TESTS_PROPERTIES(fedbat3m_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(fedbat4_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "fedbat4")
SET_TESTS_PROPERTIES(fedbat4_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(freuden_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "freuden")
SET_TESTS_PROPERTIES(freuden_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(freudenstein_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "freudenstein")
SET_TESTS_PROPERTIES(freudenstein_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(ftlos1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "ftlos1")
SET_TESTS_PROPERTIES(ftlos1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(ftlos2_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "ftlos2")
SET_TESTS_PROPERTIES(ftlos2_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(ftlos2_nlp_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "ftlos2_nlp")
SET_TESTS_PROPERTIES(ftlos2_nlp_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(ftlos3_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "ftlos3")
SET_TESTS_PROPERTIES(ftlos3_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(ftlos4_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "ftlos4")
SET_TESTS_PROPERTIES(ftlos4_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(hang_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "hang")
SET_TESTS_PROPERTIES(hang_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(helical_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "helical")
SET_TESTS_PROPERTIES(helical_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(hydroscal_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "hydroscal")
SET_TESTS_PROPERTIES(hydroscal_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(kite_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "kite")
SET_TESTS_PROPERTIES(kite_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(lbat_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "lbat")
SET_TESTS_PROPERTIES(lbat_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(macro1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "macro1")
SET_TESTS_PROPERTIES(macro1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(macro2_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "macro2")
SET_TESTS_PROPERTIES(macro2_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(macro3_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "macro3")
SET_TESTS_PROPERTIES(macro3_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(macro4_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "macro4")
SET_TESTS_PROPERTIES(macro4_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(macro5_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "macro5")
SET_TESTS_PROPERTIES(macro5_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(maratos_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "maratos")
SET_TESTS_PROPERTIES(maratos_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(nlbat_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "nlbat")
SET_TESTS_PROPERTIES(nlbat_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(nlp1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "nlp1")
SET_TESTS_PROPERTIES(nlp1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(nlp2_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "nlp2")
SET_TESTS_PROPERTIES(nlp2_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(nlp3_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "nlp3")
SET_TESTS_PROPERTIES(nlp3_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(nlp4_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "nlp4")
SET_TESTS_PROPERTIES(nlp4_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(nmpc1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "nmpc1")
SET_TESTS_PROPERTIES(nmpc1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(ocean3a_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "ocean3a")
SET_TESTS_PROPERTIES(ocean3a_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(ocean3b_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "ocean3b")
SET_TESTS_PROPERTIES(ocean3b_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(optcar_lego_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "optcar_lego")
SET_TESTS_PROPERTIES(optcar_lego_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(orbit_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "orbit")
SET_TESTS_PROPERTIES(orbit_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(pbreac_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "pbreac")
SET_TESTS_PROPERTIES(pbreac_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(powerkite_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "powerkite")
SET_TESTS_PROPERTIES(powerkite_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(qlin_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "qlin")
SET_TESTS_PROPERTIES(qlin_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(reactdiff_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "reactdiff")
SET_TESTS_PROPERTIES(reactdiff_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(reentry_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "reentry")
SET_TESTS_PROPERTIES(reentry_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(rob2link_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "rob2link")
SET_TESTS_PROPERTIES(rob2link_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(rob2link_flex_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "rob2link_flex")
SET_TESTS_PROPERTIES(rob2link_flex_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(rob3link_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "rob3link")
SET_TESTS_PROPERTIES(rob3link_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(rob3link_flex_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "rob3link_flex")
SET_TESTS_PROPERTIES(rob3link_flex_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(rosen_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "rosen")
SET_TESTS_PROPERTIES(rosen_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(singular_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "singular")
SET_TESTS_PROPERTIES(singular_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(skeleton_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "skeleton")
SET_TESTS_PROPERTIES(skeleton_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(smb_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "smb")
SET_TESTS_PROPERTIES(smb_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp1")
SET_TESTS_PROPERTIES(stp1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp1_gn_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp1_gn")
SET_TESTS_PROPERTIES(stp1_gn_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp2a_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp2a")
SET_TESTS_PROPERTIES(stp2a_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp2b_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp2b")
SET_TESTS_PROPERTIES(stp2b_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp2c_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp2c")
SET_TESTS_PROPERTIES(stp2c_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp2d_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp2d")
SET_TESTS_PROPERTIES(stp2d_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp2e_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp2e")
SET_TESTS_PROPERTIES(stp2e_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp3_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp3")
SET_TESTS_PROPERTIES(stp3_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp3_gn_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp3_gn")
SET_TESTS_PROPERTIES(stp3_gn_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp4a_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp4a")
SET_TESTS_PROPERTIES(stp4a_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp4a_gn_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp4a_gn")
SET_TESTS_PROPERTIES(stp4a_gn_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp4b_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp4b")
SET_TESTS_PROPERTIES(stp4b_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(swtball_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "swtball")
SET_TESTS_PROPERTIES(swtball_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(tocar1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "tocar1")
SET_TESTS_PROPERTIES(tocar1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(tocar2_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "tocar2")
SET_TESTS_PROPERTIES(tocar2_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(tocar3_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "tocar3")
SET_TESTS_PROPERTIES(tocar3_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(tolin1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "tolin1")
SET_TESTS_PROPERTIES(tolin1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(tolin2_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "tolin2")
SET_TESTS_PROPERTIES(tolin2_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(tolos1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "tolos1")
SET_TESTS_PROPERTIES(tolos1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(tolos2_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "tolos2")
SET_TESTS_PROPERTIES(tolos2_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(tolos3_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "tolos3")
SET_TESTS_PROPERTIES(tolos3_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(tolos4_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "tolos4")
SET_TESTS_PROPERTIES(tolos4_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(twobat1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "twobat1")
SET_TESTS_PROPERTIES(twobat1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(twobat2_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "twobat2")
SET_TESTS_PROPERTIES(twobat2_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(unload1_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "unload1")
SET_TESTS_PROPERTIES(unload1_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(unload2_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "unload2")
SET_TESTS_PROPERTIES(unload2_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(vdpol_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "vdpol")
SET_TESTS_PROPERTIES(vdpol_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(watson_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "watson")
SET_TESTS_PROPERTIES(watson_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(wood_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "wood")
SET_TESTS_PROPERTIES(wood_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(oven_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "oven")
SET_TESTS_PROPERTIES(oven_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(energy_f77_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "energy_f77")
SET_TESTS_PROPERTIES(energy_f77_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(energy_lsq_f77_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "energy_lsq_f77")
SET_TESTS_PROPERTIES(energy_lsq_f77_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(inventory_f77_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "inventory_f77")
SET_TESTS_PROPERTIES(inventory_f77_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(rocket_f77_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "rocket_f77")
SET_TESTS_PROPERTIES(rocket_f77_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
ADD_TEST(stp3_f77_test "/home/yevyes/MUSCOD-II/MC2/Release/bin/muscod_release" "stp3_f77")
SET_TESTS_PROPERTIES(stp3_f77_test PROPERTIES  PASS_REGULAR_EXPRESSION "convergence achieved")
